### ISSUE TITLE
Não conecta com novos números

### ISSUE THREAD

**Issue by DavidsonGomes** [canove/whaticket-community#489]
Desde ontem não consigo conectar mais números, eu escaneio o código QR mas não conecta, no celular aparece o status como ativo, mas não conecta na plataforma.

**Comment by CSFelix** [comment]
> **Mesmo problema aqui, no meu aparece esta mensagem de erro:**

```
C:\whaticket\backend\node_modules\whatsapp-web.js\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:221
            throw new Error('Evaluation failed: ' + helper_js_1.helper.getExceptionMessage(exceptionDetails));
                  ^

Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'default')
    at __puppeteer_evaluation_script__:14:123
    at ExecutionContext._evaluateInternal (C:\whaticket\backend\node_modules\whatsapp-web.js\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:221:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ExecutionContext.evaluate (C:\whaticket\backend\node_on\ExecutionContext.js:110:16)    at async Client.initialize (C:\whaticket\backend\node_modules\whatsapp-web.js\src\Client.js:267:9)

Node.js v18.12.0
[nodemon] app crashed - waiting for file changes before starting...
```

![image](https://user-images.githubusercontent.com/57205604/201665684-af2d2b5f-809f-4e86-80c3-abecc7714fc8.png)

**Comment by CSFelix** [comment]
> **Check out this issue [Problema ao Conectar Novos Números](https://github.com/canove/whaticket-community/issues/486) and your problem will be fixed.**

**Comment by allgood** [comment]
duplicate of #486
