### ISSUE TITLE
[nodemon] app crashed - waiting for file changes before starting...

### ISSUE THREAD

**Issue by Guiviniac** [canove/whaticket-community#516]
require() of ES modules is not supported.
require() of /home/ittnet/ITWPP/backend/node_modules/multer/index.js from /home/ittnet/ITWPP/backend/dist/config/upload.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /home/ittnet/ITWPP/backend/node_modules/multer/package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1015:13)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/ittnet/ITWPP/backend/dist/config/upload.js:7:34)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/ittnet/ITWPP/backend/dist/app.js:42:34)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/ittnet/ITWPP/backend/dist/server.js:7:31)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10) {
  code: 'ERR_REQUIRE_ESM'

Quando eu vou dar um start do backend do Whaticket , a mensagem acima aparece e o app não inicia, alguem poderia me ajudar??Estou fazendo a instalação no Ubuntu LTS 22.04.

**Comment by DevShop1251** [comment]
Estou com o mesmo problema. Já conseguiu uma solução?

**Comment by Guiviniac** [comment]
> Nunca, até hoje sem funcionar

**Comment by DevShop1251** [comment]
O meu acabou de dar esse problema, reinstalei o banco de dados e voltou a funcionar.

**Comment by DevShop1251** [comment]
Bom dia, funcionou quando alterou o arquivo Injected.js?
