### ISSUE TITLE
Nao envia mais mensagens

### ISSUE THREAD

**Issue by cronojho** [canove/whaticket-community#551]
Olá pessoal estou recebendo o erro 400 no backend ao enviar mensagem.

poderia ter algo a ver com as cobranças na API?

**Comment by cronojho** [comment]
Vamos lá, encaminhei um teste pelo whaticket, e ja refiz as conexões com o whatsapp, mas mesmo assim continua com o erro,

Esse erro começou "do nada" enquanto utilizava a aplicação ja fazem 2 meses, segue print dos logs:

![image](https://github.com/canove/whaticket-community/assets/100284894/2f1b7eda-aa73-4e27-8be4-54645af729c3)

1|whaticket-backend  | [1686084755520] WARN:
1|whaticket-backend  |     message: "ERR_SENDING_WAPP_MSG"
1|whaticket-backend  |     statusCode: 400

LOGS:

/home/netek/.pm2/logs/whaticket-frontend-error.log last 15 lines:
0|whaticke | Error: ENOENT: no such file or directory, stat '/whaticket/frontend/build/index.html'
0|whaticke | Error: ENOENT: no such file or directory, stat '/whaticket/frontend/build/index.html'
0|whaticke | Error: ENOENT: no such file or directory, stat '/whaticket/frontend/build/index.html'

/home/netek/.pm2/logs/whaticket-backend-error.log last 15 lines:
1|whaticke |     at trim_prefix (/whaticket/backend/node_modules/express/lib/router/index.js:326:13)
1|whaticke |     at /whaticket/backend/node_modules/express/lib/router/index.js:286:9
1|whaticke |     at Function.process_params (/whaticket/backend/node_modules/express/lib/router/index.js:346:12)
1|whaticke |     at next (/whaticket/backend/node_modules/express/lib/router/index.js:280:10)
1|whaticke |     at /whaticket/backend/node_modules/@sentry/node/dist/handlers.js:231:17
1|whaticke |     at Hub.withScope (/whaticket/backend/node_modules/@sentry/hub/dist/hub.js:88:13)
1|whaticke |     at callOnHub (/whaticket/backend/node_modules/@sentry/minimal/dist/index.js:18:28)
1|whaticke |     at Object.withScope (/whaticket/backend/node_modules/@sentry/minimal/dist/index.js:166:5)
1|whaticke |     at sentryErrorMiddleware (/whaticket/backend/node_modules/@sentry/node/dist/handlers.js:221:20)
1|whaticke |     at newFn (/whaticket/backend/node_modules/express-async-errors/index.js:16:20)
1|whaticke |     at Layer.handle_error (/whaticket/backend/node_modules/express/lib/router/layer.js:71:5)
1|whaticke |     at trim_prefix (/whaticket/backend/node_modules/express/lib/router/index.js:326:13)
1|whaticke |     at /whaticket/backend/node_modules/express/lib/router/index.js:286:9
1|whaticke |     at Function.process_params (/whaticket/backend/node_modules/express/lib/router/index.js:346:12)
1|whaticke |     at Domain.next (/whaticket/backend/node_modules/express/lib/router/index.js:280:10)

**Comment by cronojho** [comment]
Solucionado atualizando o web js package
