### ISSUE TITLE
Apos baixar ultima release nao instala mais erro SyntaxError: Unexpected token .

### ISSUE THREAD

**Issue by lidernetworktecnologia** [canove/whaticket-community#568]
/home/lider/wpp/backend/node_modules/whatsapp-web.js/src/structures/Message.js:171
            fromId: data.from?._serialized ? data.from._serialized : data.from,
                              ^

SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/lider/wpp/backend/node_modules/whatsapp-web.js/src/structures/Chat.js:4:17)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/lider/wpp/backend/node_modules/whatsapp-web.js/src/structures/PrivateChat.js:3:14)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by allgood** [comment]
Confere a versão do teu nodejs.

o recurso de "optional chaining operator" ( ?. ) é suportado apenas a partir do nodejs 14

**Comment by lidernetworktecnologia** [comment]
Muito obg pela ajuda era isso mesmo!
