### ISSUE TITLE
updated  whatsapp-web.js -  1.23.0 after not working

### ISSUE THREAD

**Issue by mallikharjuna-wq** [canove/whaticket-community#631]
![image_2024_04_05T05_50_34_882Z](https://github.com/canove/whaticket-community/assets/60838207/9baad5e8-8f50-4bf8-a154-a49a85a34835)
![image](https://github.com/canove/whaticket-community/assets/60838207/2569eb0f-6ba0-488a-93f7-b6a7fa43295f)

step1:
add connection throw error below

UnhandledPromiseRejectionWarning: TypeError: Cannot read property '1' of null
    at LocalWebCache.persist (C:\malli backup\Travel Projects\travel-wtchat-backend\node_modules\whatsapp-web.js\src\webCache\LocalWebCache.js:34:69)
    at C:\malli backup\Travel Projects\travel-wtchat-backend\node_modules\whatsapp-web.js\src\Client.js:744:36
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(node:10512) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:10512) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:10512) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'push')
    at fillModuleArray (eval at <anonymous> (:2:5), <anonymous>:6:74)
    at moduleRaid (eval at <anonymous> (:2:5), <anonymous>:15:3)
    at __puppeteer_evaluation_script__:4:17
    at ExecutionContext._evaluateInternal (C:\malli backup\Travel Projects\travel-wtchat-backend\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:221:19)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async ExecutionContext.evaluate (C:\malli backup\Travel Projects\travel-wtchat-backend\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:110:16)
    at async Client.initialize (C:\malli backup\Travel Projects\travel-wtchat-backend\node_modules\whatsapp-web.js\src\Client.js:323:9)
(node:10512) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)

ste 2: connect on mobile connection added but whatsapp qr show not show connected or signal marks

UnhandledPromiseRejectionWarning: TypeError: Cannot read property '1' of null
    at LocalWebCache.persist (C:\malli backup\Travel Projects\travel-wtchat-backend\node_modules\whatsapp-web.js\src\webCache\LocalWebCache.js:34:69)
    at C:\malli backup\Travel Projects\travel-wtchat-backend\node_modules\whatsapp-web.js\src\Client.js:744:36
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(node:10512) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 7)
(node:10512) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'default')
    at __puppeteer_evaluation_script__:5:95
    at ExecutionContext._evaluateInternal (C:\malli backup\Travel Projects\travel-wtchat-backend\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:221:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async ExecutionContext.evaluate (C:\malli backup\Travel Projects\travel-wtchat-backend\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:110:16)
    at async Client.initialize (C:\malli backup\Travel Projects\travel-wtchat-backend\node_modules\whatsapp-web.js\src\Client.js:323:9)
(node:10512) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 8)
(node:10512) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '1' of null
    at LocalWebCache.persist (C:\malli backup\Travel Projects\travel-wtchat-backend\node_modules\whatsapp-web.js\src\webCache\LocalWebCache.js:34:69)
    at C:\malli backup\Travel Projects\travel-wtchat-backend\node_modules\whatsapp-web.js\src\Client.js:744:36
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(node:10512) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 10)

**Comment by lidernetworktecnologia** [comment]
Mesmo problema aqui

**Comment by mallikharjuna-wq** [comment]
> Same problem here

any other solutions

**Comment by caiot5** [comment]
Mesma coisa aqui.

**Comment by mallikharjuna-wq** [comment]
> Same problem here

The tip of @lidernetworktecnologia. It worked for me, but for it to work I didn't use npm install, I directly changed the package.json file with the correct version, getting: "whatsapp-web.js": "^1.23.1-alpha.5"
then removed the directory node_modules and installed it, after that I changed the src/libs/wbot.ts file as below:

const wwebVersion = '2.2407.3';
const wbot: Session = new Client({
session: sessionCfg,
authStrategy: new LocalAuth({clientId: 'bd_'+whatsapp.id}),
puppeteer: {
executablePath: process.env.CHROME_BIN || undefined,
// @ts-ignore
browserWSEndpoint: process.env.CHROME_WS || undefined,
args: args.split(' ')
},
webVersionCache: {
type: 'remote',
remotePath: https://raw.githubusercontent.com/wppconnect-team/wa-version/main/html/${wwebVersion}.html,
},
});
It works, thanks for your assistance.

**Comment by lidernetworktecnologia** [comment]
Hoje voltou o problema e agora saiu a  whatsapp-web.js1.23.1-alpha.6 e mesmo usando a ultima versao nao funciona mais retorno mesmo erro ao ler qrcode. Alguem conseguiu resolver apos cair novamente?

**Comment by rogeriosims** [comment]
Estou com o mesmo problema.

**Comment by Revolutionnnn** [comment]
I have the same error
